version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "9000:9000"
      - "9000:9000/udp"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development